### ISSUE TITLE
Comparação do StereoType usando equalsIgnoreCase

### ISSUE THREAD

**Issue by ViniciusAz** [derickpg/AstahRename#3]
Usar 
`"create".equalsIgnoreCase(variavel)`
no lugar de 
`variável.equals("create") ou variável.equals("Create")`

**Comment by derickpg** [comment]
Alterada a linha de código para comparação com equalsIgnoreCase.

Novo trecho: 

`"create".equalsIgnoreCase(is[j])`

**Comment by derickpg** [comment]
- [x] Correção aplicada.

- [x] Teste aprovado.

- [x] Realizado commit da pasta do projeto e na release.
