### ISSUE TITLE
Testar .jar da release 1.0

### ISSUE THREAD

**Issue by derickpg** [derickpg/AstahRename#4]
Realizar o teste em um novo computador do .jar que está na release.

**Comment by ViniciusAz** [comment]
Release testada conforme o planejamento:

> Classes:
 Pessoa ___________
    - String nome
    + 'create' Pessoa()
    + String getNome()
 Clientes ___________
    - Pessoa cli
    - List'Pessoa' lista
    + 'create' Clientes()
    + Pessoa busca(String nome)
    + void novo(Pessoa)]
 Main ___________
    - Clientes cli

- [x] Alterar "Produto" (não existe)
Expectativa: Mensagem de erro "não existe"
- [x] Alterar Pessoa com nome "Clientes" (já existe)
Expectativa: Mensagem de erro "classe ja existe"
- [x] Alterar Main para "Main"
Expectativa: Mensagem de erro "o nome deve ser diferente"
Resultado: Mensagem de erro "classe já existe" 🐞 
 
- [x] Alterar Clientes para "ListaCliente"
Expectativa: mudar nome e construtores, Mensagem "nome alterado com sucesso, construtores alterados"
- [x] Alterar Pessoa para "Cliente"
Expectativa: alterar nome, construtores, ***referencias em outras classes (atributos, retornos e parâmetros)
Resultado: mudou o nome e o construtor

*** referencias não implementado nesta versão

**Comment by derickpg** [comment]
Foi corrigido o bug com a inclusão de mais uma verificação e uma mensagem a mais.
