### ISSUE TITLE
🐞 Ajuste renomear com mesmo nome

### ISSUE THREAD

**Issue by ViniciusAz** [derickpg/AstahRename#7]
Ajuste de erro encontrado no teste #4 , que ao tentar renomear o nome de uma classe para o mesmo nome deveria aparecer o alerta de "o nome deve ser diferente"
Atualmente ele mostra "classe já existe"

**Comment by derickpg** [comment]
Inclusão de uma nova verificação para caso os nomes sejam iguais.

**Comment by derickpg** [comment]
Realizado o commit da pasta do projeto e do .jar .
